# Site settings
# in the templates available like {{ site.myvariable }}.
title: Kazbek Abraliev's Portfolio.
email: k@abraliev.com
brand: Kazbek Abraliev
headline: front end web developer
description: This web site provides information about Kazbek Abraliev, web developer based in Syracuse NY 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abraliev.com" # the base hostname & protocol for your site
copyright: 2017 StartFast Code, Syracuse, NY.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 356331

# Contacts
email: k@abraliev.com
phone: +1.916.717.1061

# Tracking
googleAnalitycsID: UA-83933844-1
